channels:
    - pytorch
    - conda-forge
    - cpape
name:
    torch-em
dependencies:
    - cudatoolkit=10.2  # set correct cuda version for your system
    # FIXME solver takes ages; try mamba?!
    # - elf
    # - numba <=0.50  # need to pin this due to skan dependency in elf
    # - affogato  # TODO need to put it on conda-forge!
    - pip
    - pytorch
    - tensorboard
    - torchvision
    - tqdm
    - pip:
        - kornia
