channels:
    - pytorch
    - conda-forge
name:
    torch-em-cpu
dependencies:
    - affogato
    - bioimageio.core >=0.4.6
    - cpuonly
    - python-elf
    - pytorch
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - kornia
