channels:
    - pytorch
    - conda-forge
    - cpape
name:
    torch-em-cpu
dependencies:
    - affogato
    - cpuonly
    - elf
    - pip
    - pytorch
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - pip:
        - kornia
