channels:
    - pytorch
    - conda-forge
name:
    torch-em
dependencies:
    - affogato
    - bioimageio.core
    - cudatoolkit>=11,<12  # set correct cuda version for your system
    - python-elf
    - pip
    - pytorch
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - pip:
        - kornia
