channels:
    - pytorch
    - conda-forge
name:
    torch-em-cpu
dependencies:
    - affogato
    - bioimageio.core
    - cpuonly
    - python-elf
    - pip
    - pytorch
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - pip:
        - kornia
