channels:
    - pytorch
    - conda-forge
    - cpape
name:
    torch-em
dependencies:
    - affogato
    - cudatoolkit=10.2  # set correct cuda version for your system
    - elf
    - pip
    - pytest
    - pytorch
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - pip:
        - kornia
