channels:
    - pytorch
    - conda-forge
    - cpape
name:
    torch-em
dependencies:
    - affogato
    - bioimageio.core
    - bioimageio.spec
    - cudatoolkit>=11  # set correct cuda version for your system
    - elf
    - pip
    - pytorch
    - tensorboard
    - tifffile
    - torchvision
    - tqdm
    - pip:
        - kornia
