channels:
    - pytorch
    - conda-forge
    - cpape
name:
    torch-em
dependencies:
    - cudatoolkit=10.2  # set correct cuda version for your system
    - elf
    - affogato
    - pip
    - pytorch
    - tensorboard
    - torchvision
    - tifffile
    - tqdm
    - pip:
        - kornia
